/* Presentation overrides retain the existing deterministic data and scoring. */
document.querySelector('.note').textContent='Built for Cal Poly builders';
document.querySelector('.hero .eyebrow').textContent='Mustang Match';
document.querySelector('.hero .lede').textContent='Turn your interests and skills into a project worth building, then find Cal Poly students who could help you build it.';
document.querySelector('.hero .btn.gold').textContent='Find My Match →';
document.querySelector('.hero .btn.alt').remove();
document.querySelector('#how').textContent='A fast build profile. Three project ideas. A team that fits.';
document.querySelector('#profile .eyebrow').textContent='1. About You';
document.querySelector('#profile h2').textContent='What are you studying and what are you good at?';
document.querySelector('.q h2').textContent='What are you studying and what are you good at?';
document.querySelector('.q .label').textContent='Area of study';
document.querySelectorAll('.steps div')[0].textContent='1. About You';
document.querySelectorAll('.steps div')[1].textContent='2. What You Want to Build';
document.querySelectorAll('.steps div')[2].textContent='3. Your Availability';
document.querySelector('.footer').textContent='Mustang Match is an independent student-built prototype. Project recommendations and demo teammate profiles are illustrative.';
const originalIdeas=ideas,originalTeam=team;
function reasons(p){const skill=p[9].find(x=>s.skills.includes(x));const interest=p[6].find(x=>s.interests.includes(x));return [`${interest?'You chose '+L(interest).toLowerCase():'Your interests'} point naturally to this problem.`,`${skill?'Your '+L(skill).toLowerCase()+' skills':'Your current skills'} give this MVP a credible first step.`,`${s.hours} hours each week is enough for a ${p[7].toLowerCase()} scope.`]}
ideas=function(){originalIdeas();const top=document.querySelector('.card.top');if(!top)return;const p=s.p||P.map(x=>[...x,ps(x)]).sort((a,b)=>b[10]-a[10])[0];top.querySelector('.ribbon').textContent='YOUR TOP MATCH';top.querySelector('.score').textContent=p[10]+'% MATCH';const why=top.querySelector('p:last-of-type');why.innerHTML='<b>Why it fits you</b><br>'+reasons(p).join('<br>');document.querySelector('#ideas .eyebrow').textContent='Your Project Matches';document.querySelector('#ideas h2').textContent='A project worth building.';};
function userSkills(){return s.skills.map(L).join(' · ')||'Your strengths'}
team=function(){originalTeam();const p=s.p,m=T.map(x=>[...x,ts(x)]).sort((a,b)=>b[8]-a[8]).slice(0,3);document.querySelector('#team .eyebrow').textContent='Meet Your Team';document.querySelector('#team h2').textContent='The people who make this idea real.';document.querySelector('.network h3').textContent='YOU → YOUR PROJECT → TEAM';document.querySelector('#picked').innerHTML=`<p class="eyebrow" style="color:#d8eddf">Selected project</p><div class="score">${p[10]}% MATCH</div><h3>${p[1]} ${p[0]}</h3><p>${p[2]}</p><p><b>What you bring</b><br>${userSkills()}</p>`;document.querySelector('#projectName').textContent=p[0];document.querySelector('#people').innerHTML=m.map(x=>{const shared=x[4].filter(v=>s.interests.includes(v)).map(L).join(', ')||'Shared goal';const added=x[3].filter(v=>!s.skills.includes(v)).map(L).join(', ')||'A compatible build pace';return `<article class="person"><b class="fit">${x[8]}%<br>COMPATIBLE</b><div class="avatar">${x[1]}</div><h3>${x[0]}</h3><p>${x[2]} · ${x[6]} hrs/week</p><p><b>Shared</b><br>${shared}</p><p><b>They bring</b><br>${added}</p></article>`}).join('');const covered=[...new Set([...s.skills,...m.flatMap(x=>x[3]),'product'])];const coverage=['product','code','design','marketing','data'].map(x=>`<span>${L(x)} ${covered.includes(x)?'✓':'○'}</span>`).join('');document.querySelector('#coverage').innerHTML=`<h3>Why This Team Works</h3><p>You bring ${userSkills().toLowerCase()}. ${m[0][0]} adds ${m[0][3].filter(v=>!s.skills.includes(v)).map(L).join(' and ')||'a matching build pace'}, while the group covers the work needed for a strong first version.</p><div class="coverage">${coverage}</div>`;const end=document.querySelector('.final');end.innerHTML=`<div><p class="eyebrow">Find Real Teammates</p><h2>Join the Mustang Match builder pool.</h2><p>Share your Cal Poly email and saved profile to be considered for future student matches.</p><form class="pool" id="pool"><input id="pool-email" type="email" required placeholder="you@calpoly.edu" aria-label="Cal Poly email"><button class="btn" type="submit">Join the Builder Pool</button><p class="msg"></p></form></div>`;document.querySelector('#pool').onsubmit=e=>{e.preventDefault();const email=document.querySelector('#pool-email'),message=e.currentTarget.querySelector('.msg');if(!email.validity.valid||!email.value.endsWith('@calpoly.edu')){message.textContent='Use a valid @calpoly.edu email address.';return}localStorage.setItem('mustang-match-pool',JSON.stringify({email:email.value,skills:s.skills,interests:s.interests,project:p[0],hours:s.hours}));message.textContent='Your profile was saved on this device. The live matching service is coming next.';email.disabled=true;e.currentTarget.querySelector('button').disabled=true;};};
